name: myafmzd
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.3
  path: ^1.9.0
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.3
  pdfx: ^2.9.2
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.1
  flutter_map: ^8.2.0
  latlong2: ^0.9.1
  flutter_map_marker_popup: ^8.0.1
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  flutter_map_animations: ^0.9.0
  flutter_map_tile_caching: ^10.1.1
  supabase_flutter: ^2.9.1
  dropdown_search: 6.0.2
  file_picker: 10.2.1
  pdfrx: ^2.1.3


  # ✅ Drift actualizado
  drift: ^2.28.0
  drift_flutter: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.28.1-dev.0
  build_runner: ^2.6.0-dev.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/reportes/
    - assets/reportes/2025-01/
    - assets/reportes/2025-02/
    - assets/reportes/2025-03/
    - assets/reportes/2025-04/
    - assets/reportes/2025-05/
    - assets/reportes/2025-06/
    - assets/reportes/reportes_index.json

