// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNzeEglAm0Oj_DLMjLNH6Hf7q-Vmds88g',
    appId: '1:92720896586:web:bd6b117e5f58f96579e4b3',
    messagingSenderId: '92720896586',
    projectId: 'myafmzd-3910b',
    authDomain: 'myafmzd-3910b.firebaseapp.com',
    storageBucket: 'myafmzd-3910b.firebasestorage.app',
    measurementId: 'G-LPTGMGZ5XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpK-3Y5_gE2DjeqD7Nk5pOw_9GKTSdY04',
    appId: '1:92720896586:android:48ee5a3e5d87f80679e4b3',
    messagingSenderId: '92720896586',
    projectId: 'myafmzd-3910b',
    storageBucket: 'myafmzd-3910b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEJbc1ylSh9yX-J9UHrOuPh5pbXUzuhU',
    appId: '1:92720896586:ios:2b481a3cfe7dcbe179e4b3',
    messagingSenderId: '92720896586',
    projectId: 'myafmzd-3910b',
    storageBucket: 'myafmzd-3910b.firebasestorage.app',
    iosBundleId: 'com.example.myafmzd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEJbc1ylSh9yX-J9UHrOuPh5pbXUzuhU',
    appId: '1:92720896586:ios:2b481a3cfe7dcbe179e4b3',
    messagingSenderId: '92720896586',
    projectId: 'myafmzd-3910b',
    storageBucket: 'myafmzd-3910b.firebasestorage.app',
    iosBundleId: 'com.example.myafmzd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNzeEglAm0Oj_DLMjLNH6Hf7q-Vmds88g',
    appId: '1:92720896586:web:48a1de38d36ba84479e4b3',
    messagingSenderId: '92720896586',
    projectId: 'myafmzd-3910b',
    authDomain: 'myafmzd-3910b.firebaseapp.com',
    storageBucket: 'myafmzd-3910b.firebasestorage.app',
    measurementId: 'G-XV33EFQT7D',
  );
}
